export const data = [
    {id : 1, time : 12, degree : 19, status : 'clear sky'},
    {id : 2, time : 13, degree : 20, status : 'few clouds'},
    {id : 3, time : 14, degree : 21, status : 'scattered clouds'},
    {id : 4, time : 15, degree : 22, status : 'broken clouds'},
    {id : 5, time : 16, degree : 23, status : 'shower rain'},
    {id : 6, time : 17, degree : 24, status : 'rain'},
    {id : 7, time : 18, degree : 24, status : 'thunderstorm'},
    {id : 8, time : 19, degree : 23, status : 'snow'},
    {id : 9, time : 20, degree : 22, status : 'mist'},
    {id : 10, time : 21, degree : 21, status : 'clear sky'},
    {id : 11, time : 22, degree : 20, status : 'few clouds'},
    {id : 12, time : 23, degree : 20, status : 'scattered clouds'},
    {id : 13, time : 0o0, degree : 19, status : 'clear sky'},
    {id : 14, time : 1, degree : 19, status : 'clear sky'},
    {id : 15, time : 2, degree : 19, status : 'clear sky'},
    {id : 16, time : 3, degree : 19, status : 'clear sky'},
    {id : 17, time : 4, degree : 19, status : 'clear sky'},
    {id : 18, time : 5, degree : 19, status : 'clear sky'},
    {id : 19, time : 6, degree : 19, status : 'clear sky'},
    {id : 20, time : 7, degree : 19, status : 'clear sky'},
    {id : 21, time : 8, degree : 19, status : 'clear sky'},
    {id : 22, time : 9, degree : 19, status : 'clear sky'},
    {id : 23, time : 10, degree : 19, status : 'clear sky'},
    {id : 24, time : 11, degree : 19, status : 'clear sky'},
]
